name: Release new AddOn version
on:
  push:
    branches:
      - master
    tags:
      #- '**'

env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GH_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # pull the repository (required)
      - uses: actions/checkout@v1

      # run release.sh without any arguments (default)
      - uses: Evonder/packager@master
        with:
          args: release.sh

      # run release.sh with arguments
      #- uses: BigWigsMods/packager@master
      #  with:
      #    args: release.sh -s        
